jobs:
  - job: CI
    pool:
      vmImage: ubuntu-latest

    steps:
      - task: UsePythonVersion@0
        displayName: "Setting Python version to 3.8 as required by functions"
        inputs:
          versionSpec: "3.10"
          architecture: "x64"

      - bash: pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
        displayName: "Installing dependencies"

      - bash: python3 -u scripts/package.py
        displayName: "Generate package"

      - task: AzureCLI@2
        inputs:
          azureSubscription: $(SC_TO_AZURE_RM)
          scriptType: "bash"
          scriptLocation: "inlineScript"
          inlineScript: |
            mssqlConnStr=$(az keyvault secret show --vault-name '$(KV_NAME)' --name '$(DB_CONN_STRING_KV_SECRET_NAME)' --query value -o tsv)
            echo MSSQL_CONNECTION_STRING=$mssqlConnStr >> .env
            cat .env

      - bash: pip install -r ./requirements.txt && alembic upgrade head
        displayName: "Run migrations"

      - task: ArchiveFiles@2
        displayName: "Archive files"
        inputs:
          rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
          includeRootFolder: false
          archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
          archiveType: zip
          replaceExistingArchive: true

      - task: AzureFunctionApp@1
        inputs:
          azureSubscription: $(SC_TO_AZURE_RM)
          appType: functionAppLinux
          appName: "$(FUNCTION_APP_NAME)"
          package: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
